name = "point_anim"
description = ""
version = "0.1.0-dev"

authors = ["Luke A. Guest"]
maintainers = ["Luke A. Guest <laguest@archeia.com>"]
maintainers-logins = ["Lucretia"]
licenses = "BSD-3-Clause"
website = ""
tags = ["opengl", "gl4"]

executables = ["point_anim"]

[[depends-on]]
sdlada = "^2.5.73"
sdlada_image = "~0.1.0-dev"
opengl = "~0.1.0-dev"

[[pins]]
# sdlada = { url='https://github.com/ada-game-framework/sdlada.git' }
# sdlada_image = { url='https://github.com/ada-game-framework/sdlada_image.git' }
opengl = { path='../../opengl' }

sdlada = { path='../../../../game-dev/sdl/sdlada' }
sdlada_image = { path='../../../../game-dev/sdl/sdlada_image' }

